#!/usr/bin/env bash

set -e

CONFIG=""
DOTBOT_DIR="dotbot"

die() { echo "ERROR: ${*}"; exit 1; }

[[ "$1" ]] && CONFIG="$1" || die "expected config file, eg: $0 install.conf.yaml"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"


# Cheat completions
echo "Downloading cheat.zsh completion"
curl -Ls https://github.com/cheat/cheat/raw/master/scripts/cheat.zsh > config/zsh/completions/_cheat

echo
echo "SpaceVim was installed, but the fonts were not installed."
echo "Consider a full manual install:"
echo "  curl -sLf https://spacevim.org/install.sh | bash"
 
