---
editor: nvim
colorize: true

# https://github.com/alecthomas/chroma/tree/master/styles
style: monokai

# One of: "terminal", "terminal256", "terminal16m"
formatter: terminal16m

cheatpaths:
  # - name: community
  #   path: ~/.dotfiles/cheat/community
  #   tags: [ community ]
  #   readonly: true

  - name: sgz
    path: ~/.dotfiles/config/cheat/sgz
    tags: [ sgz ]
    readonly: false

